import React, { useState, useEffect } from 'react';
import './Register.css';

// Tüm şehir ve ilçe bilgilerini içeren obje
const allCitiesAndDistricts = {
    "ADANA": [
        "ALADAĞ",
        "CEYHAN",
        "ÇUKUROVA",
        "FEKE",
        "İMAMOĞLU",
        "KARAİSALI",
        "KARATAŞ",
        "KOZAN",
        "POZANTI",
        "SAİMBEYLİ",
        "SARIÇAM",
        "SEYHAN",
        "TUFANBEYLİ",
        "YUMURTALIK",
        "YÜREĞİR"
      ],
      "ADIYAMAN": [
        "BESNİ",
        "ÇELİKHAN",
        "GERGER",
        "GÖLBAŞI",
        "KAHTA",
        "MERKEZ",
        "SAMSAT",
        "SİNCİK",
        "TUT"
      ],
      "AFYONKARAHİSAR": [
        "BAŞMAKÇI",
        "BAYAT",
        "BOLVADİN",
        "ÇAY",
        "ÇOBANLAR",
        "DAZKIRI",
        "DİNAR",
        "EMİRDAĞ",
        "EVCİLER",
        "HOCALAR",
        "İHSANİYE",
        "İSCEHİSAR",
        "KIZILÖREN",
        "MERKEZ",
        "SANDIKLI",
        "SİNANPAŞA",
        "SULTANDAĞI",
        "ŞUHUT"
      ],
      "AĞRI": [
        "DİYADİN",
        "DOĞUBAYAZIT",
        "ELEŞKİRT",
        "HAMUR",
        "MERKEZ",
        "PATNOS",
        "TAŞLIÇAY",
        "TUTAK"
      ],
      "AKSARAY": [
        "AĞAÇÖREN",
        "ESKİL",
        "GÜLAĞAÇ",
        "GÜZELYURT",
        "MERKEZ",
        "ORTAKÖY",
        "SARIYAHŞİ",
        "SULTANHANI"
      ],
      "AMASYA": [
        "GÖYNÜCEK",
        "GÜMÜŞHACIKÖY",
        "HAMAMÖZÜ",
        "MERKEZ",
        "MERZİFON",
        "SULUOVA",
        "TAŞOVA"
      ],
      "ANKARA": [
        "AKYURT",
        "ALTINDAĞ",
        "AYAŞ",
        "BALA",
        "BEYPAZARI",
        "ÇAMLIDERE",
        "ÇANKAYA",
        "ÇUBUK",
        "ELMADAĞ",
        "ETİMESGUT",
        "EVREN",
        "GÖLBAŞI",
        "GÜDÜL",
        "HAYMANA",
        "KAHRAMANKAZAN",
        "KALECİK",
        "KEÇİÖREN",
        "KIZILCAHAMAM",
        "MAMAK",
        "NALLIHAN",
        "POLATLI",
        "PURSAKLAR",
        "SİNCAN",
        "ŞEREFLİKOÇHİSAR",
        "YENİMAHALLE"
      ],
      "ANTALYA": [
        "AKSEKİ",
        "AKSU",
        "ALANYA",
        "DEMRE",
        "DÖŞEMEALTI",
        "ELMALI",
        "FİNİKE",
        "GAZİPAŞA",
        "GÜNDOĞMUŞ",
        "İBRADI",
        "KAŞ",
        "KEMER",
        "KEPEZ",
        "KONYAALTI",
        "KORKUTELİ",
        "KUMLUCA",
        "MANAVGAT",
        "MURATPAŞA",
        "SERİK"
      ],
      "ARDAHAN": [
        "ÇILDIR",
        "DAMAL",
        "GÖLE",
        "HANAK",
        "MERKEZ",
        "POSOF"
      ],
      "ARTVİN": [
        "ARDANUÇ",
        "ARHAVİ",
        "BORÇKA",
        "HOPA",
        "KEMALPAŞA",
        "MERKEZ",
        "MURGUL",
        "ŞAVŞAT",
        "YUSUFELİ"
      ],
      "AYDIN": [
        "BOZDOĞAN",
        "BUHARKENT",
        "ÇİNE",
        "DİDİM",
        "EFELER",
        "GERMENCİK",
        "İNCİRLİOVA",
        "KARACASU",
        "KARPUZLU",
        "KOÇARLI",
        "KÖŞK",
        "KUŞADASI",
        "KUYUCAK",
        "NAZİLLİ",
        "SÖKE",
        "SULTANHİSAR",
        "YENİPAZAR"
      ],
      "BALIKESİR": [
        "ALTIEYLÜL",
        "AYVALIK",
        "BALYA",
        "BANDIRMA",
        "BİGADİÇ",
        "BURHANİYE",
        "DURSUNBEY",
        "EDREMİT",
        "ERDEK",
        "GÖMEÇ",
        "GÖNEN",
        "HAVRAN",
        "İVRİNDİ",
        "KARESİ",
        "KEPSUT",
        "MANYAS",
        "MARMARA",
        "SAVAŞTEPE",
        "SINDIRGI",
        "SUSURLUK"
      ],
      "BARTIN": [
        "AMASRA",
        "KURUCAŞİLE",
        "MERKEZ",
        "ULUS"
      ],
      "BATMAN": [
        "BEŞİRİ",
        "GERCÜŞ",
        "HASANKEYF",
        "KOZLUK",
        "MERKEZ",
        "SASON"
      ],
      "BAYBURT": [
        "AYDINTEPE",
        "DEMİRÖZÜ",
        "MERKEZ"
      ],
      "BİLECİK": [
        "BOZÜYÜK",
        "GÖLPAZARI",
        "İNHİSAR",
        "MERKEZ",
        "OSMANELİ",
        "PAZARYERİ",
        "SÖĞÜT",
        "YENİPAZAR"
      ],
      "BİNGÖL": [
        "ADAKLI",
        "GENÇ",
        "KARLIOVA",
        "KİĞI",
        "MERKEZ",
        "SOLHAN",
        "YAYLADERE",
        "YEDİSU"
      ],
      "BİTLİS": [
        "ADİLCEVAZ",
        "AHLAT",
        "GÜROYMAK",
        "HİZAN",
        "MERKEZ",
        "MUTKİ",
        "TATVAN"
      ],
      "BOLU": [
        "DÖRTDİVAN",
        "GEREDE",
        "GÖYNÜK",
        "KIBRISCIK",
        "MENGEN",
        "MERKEZ",
        "MUDURNU",
        "SEBEN",
        "YENİÇAĞA"
      ],
      "BURDUR": [
        "AĞLASUN",
        "ALTINYAYLA",
        "BUCAK",
        "ÇAVDIR",
        "ÇELTİKÇİ",
        "GÖLHİSAR",
        "KARAMANLI",
        "KEMER",
        "MERKEZ",
        "TEFENNİ",
        "YEŞİLOVA"
      ],
      "BURSA": [
        "BÜYÜKORHAN",
        "GEMLİK",
        "GÜRSU",
        "HARMANCIK",
        "İNEGÖL",
        "İZNİK",
        "KARACABEY",
        "KELES",
        "KESTEL",
        "MUDANYA",
        "MUSTAFAKEMALPAŞA",
        "NİLÜFER",
        "ORHANELİ",
        "ORHANGAZİ",
        "OSMANGAZİ",
        "YENİŞEHİR",
        "YILDIRIM"
      ],
      "ÇANAKKALE": [
        "AYVACIK",
        "BAYRAMİÇ",
        "BİGA",
        "BOZCAADA",
        "ÇAN",
        "ECEABAT",
        "EZİNE",
        "GELİBOLU",
        "GÖKÇEADA",
        "LAPSEKİ",
        "MERKEZ",
        "YENİCE"
      ],
      "ÇANKIRI": [
        "ATKARACALAR",
        "BAYRAMÖREN",
        "ÇERKEŞ",
        "ELDİVAN",
        "ILGAZ",
        "KIZILIRMAK",
        "KORGUN",
        "KURŞUNLU",
        "MERKEZ",
        "ORTA",
        "ŞABANÖZÜ",
        "YAPRAKLI"
      ],
      "ÇORUM": [
        "ALACA",
        "BAYAT",
        "BOĞAZKALE",
        "DODURGA",
        "İSKİLİP",
        "KARGI",
        "LAÇİN",
        "MECİTÖZÜ",
        "MERKEZ",
        "OĞUZLAR",
        "ORTAKÖY",
        "OSMANCIK",
        "SUNGURLU",
        "UĞURLUDAĞ"
      ],
      "DENİZLİ": [
        "ACIPAYAM",
        "BABADAĞ",
        "BAKLAN",
        "BEKİLLİ",
        "BEYAĞAÇ",
        "BOZKURT",
        "BULDAN",
        "ÇAL",
        "ÇAMELİ",
        "ÇARDAK",
        "ÇİVRİL",
        "GÜNEY",
        "HONAZ",
        "KALE",
        "MERKEZEFENDİ",
        "PAMUKKALE",
        "SARAYKÖY",
        "SERİNHİSAR",
        "TAVAS"
      ],
      "DİYARBAKIR": [
        "BAĞLAR",
        "BİSMİL",
        "ÇERMİK",
        "ÇINAR",
        "ÇÜNGÜŞ",
        "DİCLE",
        "EĞİL",
        "ERGANİ",
        "HANİ",
        "HAZRO",
        "KAYAPINAR",
        "KOCAKÖY",
        "KULP",
        "LİCE",
        "SİLVAN",
        "SUR",
        "YENİŞEHİR"
      ],
      "DÜZCE": [
        "AKÇAKOCA",
        "CUMAYERİ",
        "ÇİLİMLİ",
        "GÖLYAKA",
        "GÜMÜŞOVA",
        "KAYNAŞLI",
        "MERKEZ",
        "YIĞILCA"
      ],
      "EDİRNE": [
        "ENEZ",
        "HAVSA",
        "İPSALA",
        "KEŞAN",
        "LALAPAŞA",
        "MERİÇ",
        "MERKEZ",
        "SÜLOĞLU",
        "UZUNKÖPRÜ"
      ],
      "ELAZIĞ": [
        "AĞIN",
        "ALACAKAYA",
        "ARICAK",
        "BASKİL",
        "KARAKOÇAN",
        "KEBAN",
        "KOVANCILAR",
        "MADEN",
        "MERKEZ",
        "PALU",
        "SİVRİCE"
      ],
      "ERZİNCAN": [
        "ÇAYIRLI",
        "İLİÇ",
        "KEMAH",
        "KEMALİYE",
        "MERKEZ",
        "OTLUKBELİ",
        "REFAHİYE",
        "TERCAN",
        "ÜZÜMLÜ"
      ],
      "ERZURUM": [
        "AŞKALE",
        "AZİZİYE",
        "ÇAT",
        "HINIS",
        "HORASAN",
        "İSPİR",
        "KARAÇOBAN",
        "KARAYAZI",
        "KÖPRÜKÖY",
        "NARMAN",
        "OLTU",
        "OLUR",
        "PALANDÖKEN",
        "PASİNLER",
        "PAZARYOLU",
        "ŞENKAYA",
        "TEKMAN",
        "TORTUM",
        "UZUNDERE",
        "YAKUTİYE"
      ],
      "ESKİŞEHİR": [
        "ALPU",
        "BEYLİKOVA",
        "ÇİFTELER",
        "GÜNYÜZÜ",
        "HAN",
        "İNÖNÜ",
        "MAHMUDİYE",
        "MİHALGAZİ",
        "MİHALIÇÇIK",
        "ODUNPAZARI",
        "SARICAKAYA",
        "SEYİTGAZİ",
        "SİVRİHİSAR",
        "TEPEBAŞI"
      ],
      "GAZİANTEP": [
        "ARABAN",
        "İSLAHİYE",
        "KARKAMIŞ",
        "NİZİP",
        "NURDAĞI",
        "OĞUZELİ",
        "ŞAHİNBEY",
        "ŞEHİTKAMİL",
        "YAVUZELİ"
      ],
      "GİRESUN": [
        "ALUCRA",
        "BULANCAK",
        "ÇAMOLUK",
        "ÇANAKÇI",
        "DERELİ",
        "DOĞANKENT",
        "ESPİYE",
        "EYNESİL",
        "GÖRELE",
        "GÜCE",
        "KEŞAP",
        "MERKEZ",
        "PİRAZİZ",
        "ŞEBİNKARAHİSAR",
        "TİREBOLU",
        "YAĞLIDERE"
      ],
      "GÜMÜŞHANE": [
        "KELKİT",
        "KÖSE",
        "KÜRTÜN",
        "MERKEZ",
        "ŞİRAN",
        "TORUL"
      ],
      "HAKKARİ": [
        "ÇUKURCA",
        "DERECİK",
        "MERKEZ",
        "ŞEMDİNLİ",
        "YÜKSEKOVA"
      ],
      "HATAY": [
        "ALTINÖZÜ",
        "ANTAKYA",
        "ARSUZ",
        "BELEN",
        "DEFNE",
        "DÖRTYOL",
        "ERZİN",
        "HASSA",
        "İSKENDERUN",
        "KIRIKHAN",
        "KUMLU",
        "PAYAS",
        "REYHANLI",
        "SAMANDAĞ",
        "YAYLADAĞI"
      ],
      "IĞDIR": [
        "ARALIK",
        "KARAKOYUNLU",
        "MERKEZ",
        "TUZLUCA"
      ],
      "ISPARTA": [
        "AKSU",
        "ATABEY",
        "EĞİRDİR",
        "GELENDOST",
        "GÖNEN",
        "KEÇİBORLU",
        "MERKEZ",
        "SENİRKENT",
        "SÜTÇÜLER",
        "ŞARKİKARAAĞAÇ",
        "ULUBORLU",
        "YALVAÇ",
        "YENİŞARBADEMLİ"
      ],
      "İSTANBUL": [
        "ADALAR",
        "ARNAVUTKÖY",
        "ATAŞEHİR",
        "AVCILAR",
        "BAĞCILAR",
        "BAHÇELİEVLER",
        "BAKIRKÖY",
        "BAŞAKŞEHİR",
        "BAYRAMPAŞA",
        "BEŞİKTAŞ",
        "BEYKOZ",
        "BEYLİKDÜZÜ",
        "BEYOĞLU",
        "BÜYÜKÇEKMECE",
        "ÇATALCA",
        "ÇEKMEKÖY",
        "ESENLER",
        "ESENYURT",
        "EYÜPSULTAN",
        "FATİH",
        "GAZİOSMANPAŞA",
        "GÜNGÖREN",
        "KADIKÖY",
        "KAĞITHANE",
        "KARTAL",
        "KÜÇÜKÇEKMECE",
        "MALTEPE",
        "PENDİK",
        "SANCAKTEPE",
        "SARIYER",
        "SİLİVRİ",
        "SULTANBEYLİ",
        "SULTANGAZİ",
        "ŞİLE",
        "ŞİŞLİ",
        "TUZLA",
        "ÜMRANİYE",
        "ÜSKÜDAR",
        "ZEYTİNBURNU"
      ],
      "İZMİR": [
        "ALİAĞA",
        "BALÇOVA",
        "BAYINDIR",
        "BAYRAKLI",
        "BERGAMA",
        "BEYDAĞ",
        "BORNOVA",
        "BUCA",
        "ÇEŞME",
        "ÇİĞLİ",
        "DİKİLİ",
        "FOÇA",
        "GAZİEMİR",
        "GÜZELBAHÇE",
        "KARABAĞLAR",
        "KARABURUN",
        "KARŞIYAKA",
        "KEMALPAŞA",
        "KINIK",
        "KİRAZ",
        "KONAK",
        "MENDERES",
        "MENEMEN",
        "NARLIDERE",
        "ÖDEMİŞ",
        "SEFERİHİSAR",
        "SELÇUK",
        "TİRE",
        "TORBALI",
        "URLA"
      ],
      "KAHRAMANMARAŞ": [
        "AFŞİN",
        "ANDIRIN",
        "ÇAĞLAYANCERİT",
        "DULKADİROĞLU",
        "EKİNÖZÜ",
        "ELBİSTAN",
        "GÖKSUN",
        "NURHAK",
        "ONİKİŞUBAT",
        "PAZARCIK",
        "TÜRKOĞLU"
      ],
      "KARABÜK": [
        "EFLANİ",
        "ESKİPAZAR",
        "MERKEZ",
        "OVACIK",
        "SAFRANBOLU",
        "YENİCE"
      ],
      "KARAMAN": [
        "AYRANCI",
        "BAŞYAYLA",
        "ERMENEK",
        "KAZIMKARABEKİR",
        "MERKEZ",
        "SARIVELİLER"
      ],
      "KARS": [
        "AKYAKA",
        "ARPAÇAY",
        "DİGOR",
        "KAĞIZMAN",
        "MERKEZ",
        "SARIKAMIŞ",
        "SELİM",
        "SUSUZ"
      ],
      "KASTAMONU": [
        "ABANA",
        "AĞLI",
        "ARAÇ",
        "AZDAVAY",
        "BOZKURT",
        "CİDE",
        "ÇATALZEYTİN",
        "DADAY",
        "DEVREKANİ",
        "DOĞANYURT",
        "HANÖNÜ",
        "İHSANGAZİ",
        "İNEBOLU",
        "KÜRE",
        "MERKEZ",
        "PINARBAŞI",
        "SEYDİLER",
        "ŞENPAZAR",
        "TAŞKÖPRÜ",
        "TOSYA"
      ],
      "KAYSERİ": [
        "AKKIŞLA",
        "BÜNYAN",
        "DEVELİ",
        "FELAHİYE",
        "HACILAR",
        "İNCESU",
        "KOCASİNAN",
        "MELİKGAZİ",
        "ÖZVATAN",
        "PINARBAŞI",
        "SARIOĞLAN",
        "SARIZ",
        "TALAS",
        "TOMARZA",
        "YAHYALI",
        "YEŞİLHİSAR"
      ],
      "KIRIKKALE": [
        "BAHŞILI",
        "BALIŞEYH",
        "ÇELEBİ",
        "DELİCE",
        "KARAKEÇİLİ",
        "KESKİN",
        "MERKEZ",
        "SULAKYURT",
        "YAHŞİHAN"
      ],
      "KIRKLARELİ": [
        "BABAESKİ",
        "DEMİRKÖY",
        "KOFÇAZ",
        "LÜLEBURGAZ",
        "MERKEZ",
        "PEHLİVANKÖY",
        "PINARHİSAR",
        "VİZE"
      ],
      "KIRŞEHİR": [
        "AKÇAKENT",
        "AKPINAR",
        "BOZTEPE",
        "ÇİÇEKDAĞI",
        "KAMAN",
        "MERKEZ",
        "MUCUR"
      ],
      "KİLİS": [
        "ELBEYLİ",
        "MERKEZ",
        "MUSABEYLİ",
        "POLATELİ"
      ],
      "KOCAELİ": [
        "BAŞİSKELE",
        "ÇAYIROVA",
        "DARICA",
        "DERİNCE",
        "DİLOVASI",
        "GEBZE",
        "GÖLCÜK",
        "İZMİT",
        "KANDIRA",
        "KARAMÜRSEL",
        "KARTEPE",
        "KÖRFEZ"
      ],
      "KONYA": [
        "AHIRLI",
        "AKÖREN",
        "AKŞEHİR",
        "ALTINEKİN",
        "BEYŞEHİR",
        "BOZKIR",
        "CİHANBEYLİ",
        "ÇELTİK",
        "ÇUMRA",
        "DERBENT",
        "DEREBUCAK",
        "DOĞANHİSAR",
        "EMİRGAZİ",
        "EREĞLİ",
        "GÜNEYSINIR",
        "HADİM",
        "HALKAPINAR",
        "HÜYÜK",
        "ILGIN",
        "KADINHANI",
        "KARAPINAR",
        "KARATAY",
        "KULU",
        "MERAM",
        "SARAYÖNÜ",
        "SELÇUKLU",
        "SEYDİŞEHİR",
        "TAŞKENT",
        "TUZLUKÇU",
        "YALIHÜYÜK",
        "YUNAK"
      ],
      "KÜTAHYA": [
        "ALTINTAŞ",
        "ASLANAPA",
        "ÇAVDARHİSAR",
        "DOMANİÇ",
        "DUMLUPINAR",
        "EMET",
        "GEDİZ",
        "HİSARCIK",
        "MERKEZ",
        "PAZARLAR",
        "SİMAV",
        "ŞAPHANE",
        "TAVŞANLI"
      ],
      "MALATYA": [
        "AKÇADAĞ",
        "ARAPGİR",
        "ARGUVAN",
        "BATTALGAZİ",
        "DARENDE",
        "DOĞANŞEHİR",
        "DOĞANYOL",
        "HEKİMHAN",
        "KALE",
        "KULUNCAK",
        "PÜTÜRGE",
        "YAZIHAN",
        "YEŞİLYURT"
      ],
      "MANİSA": [
        "AHMETLİ",
        "AKHİSAR",
        "ALAŞEHİR",
        "DEMİRCİ",
        "GÖLMARMARA",
        "GÖRDES",
        "KIRKAĞAÇ",
        "KÖPRÜBAŞI",
        "KULA",
        "SALİHLİ",
        "SARIGÖL",
        "SARUHANLI",
        "SELENDİ",
        "SOMA",
        "ŞEHZADELER",
        "TURGUTLU",
        "YUNUSEMRE"
      ],
      "MARDİN": [
        "ARTUKLU",
        "DARGEÇİT",
        "DERİK",
        "KIZILTEPE",
        "MAZIDAĞI",
        "MİDYAT",
        "NUSAYBİN",
        "ÖMERLİ",
        "SAVUR",
        "YEŞİLLİ"
      ],
      "MERSİN": [
        "AKDENİZ",
        "ANAMUR",
        "AYDINCIK",
        "BOZYAZI",
        "ÇAMLIYAYLA",
        "ERDEMLİ",
        "GÜLNAR",
        "MEZİTLİ",
        "MUT",
        "SİLİFKE",
        "TARSUS",
        "TOROSLAR",
        "YENİŞEHİR"
      ],
      "MUĞLA": [
        "BODRUM",
        "DALAMAN",
        "DATÇA",
        "FETHİYE",
        "KAVAKLIDERE",
        "KÖYCEĞİZ",
        "MARMARİS",
        "MENTEŞE",
        "MİLAS",
        "ORTACA",
        "SEYDİKEMER",
        "ULA",
        "YATAĞAN"
      ],
      "MUŞ": [
        "BULANIK",
        "HASKÖY",
        "KORKUT",
        "MALAZGİRT",
        "MERKEZ",
        "VARTO"
      ],
      "NEVŞEHİR": [
        "ACIGÖL",
        "AVANOS",
        "DERİNKUYU",
        "GÜLŞEHİR",
        "HACIBEKTAŞ",
        "KOZAKLI",
        "MERKEZ",
        "ÜRGÜP"
      ],
      "NİĞDE": [
        "ALTUNHİSAR",
        "BOR",
        "ÇAMARDI",
        "ÇİFTLİK",
        "MERKEZ",
        "ULUKIŞLA"
      ],
      "ORDU": [
        "AKKUŞ",
        "ALTINORDU",
        "AYBASTI",
        "ÇAMAŞ",
        "ÇATALPINAR",
        "ÇAYBAŞI",
        "FATSA",
        "GÖLKÖY",
        "GÜLYALI",
        "GÜRGENTEPE",
        "İKİZCE",
        "KABADÜZ",
        "KABATAŞ",
        "KORGAN",
        "KUMRU",
        "MESUDİYE",
        "PERŞEMBE",
        "ULUBEY",
        "ÜNYE"
      ],
      "OSMANİYE": [
        "BAHÇE",
        "DÜZİÇİ",
        "HASANBEYLİ",
        "KADİRLİ",
        "MERKEZ",
        "SUMBAS",
        "TOPRAKKALE"
      ],
      "RİZE": [
        "ARDEŞEN",
        "ÇAMLIHEMŞİN",
        "ÇAYELİ",
        "DEREPAZARI",
        "FINDIKLI",
        "GÜNEYSU",
        "HEMŞİN",
        "İKİZDERE",
        "İYİDERE",
        "KALKANDERE",
        "MERKEZ",
        "PAZAR"
      ],
      "SAKARYA": [
        "ADAPAZARI",
        "AKYAZI",
        "ARİFİYE",
        "ERENLER",
        "FERİZLİ",
        "GEYVE",
        "HENDEK",
        "KARAPÜRÇEK",
        "KARASU",
        "KAYNARCA",
        "KOCAALİ",
        "PAMUKOVA",
        "SAPANCA",
        "SERDİVAN",
        "SÖĞÜTLÜ",
        "TARAKLI"
      ],
      "SAMSUN": [
        "19 MAYIS",
        "ALAÇAM",
        "ASARCIK",
        "ATAKUM",
        "AYVACIK",
        "BAFRA",
        "CANİK",
        "ÇARŞAMBA",
        "HAVZA",
        "İLKADIM",
        "KAVAK",
        "LADİK",
        "SALIPAZARI",
        "TEKKEKÖY",
        "TERME",
        "VEZİRKÖPRÜ",
        "YAKAKENT"
      ],
      "SİİRT": [
        "BAYKAN",
        "ERUH",
        "KURTALAN",
        "MERKEZ",
        "PERVARİ",
        "ŞİRVAN",
        "TİLLO"
      ],
      "SİNOP": [
        "AYANCIK",
        "BOYABAT",
        "DİKMEN",
        "DURAĞAN",
        "ERFELEK",
        "GERZE",
        "MERKEZ",
        "SARAYDÜZÜ",
        "TÜRKELİ"
      ],
      "SİVAS": [
        "AKINCILAR",
        "ALTINYAYLA",
        "DİVRİĞİ",
        "DOĞANŞAR",
        "GEMEREK",
        "GÖLOVA",
        "GÜRÜN",
        "HAFİK",
        "İMRANLI",
        "KANGAL",
        "KOYULHİSAR",
        "MERKEZ",
        "SUŞEHRİ",
        "ŞARKIŞLA",
        "ULAŞ",
        "YILDIZELİ",
        "ZARA"
      ],
      "ŞANLIURFA": [
        "AKÇAKALE",
        "BİRECİK",
        "BOZOVA",
        "CEYLANPINAR",
        "EYYÜBİYE",
        "HALFETİ",
        "HALİLİYE",
        "HARRAN",
        "HİLVAN",
        "KARAKÖPRÜ",
        "SİVEREK",
        "SURUÇ",
        "VİRANŞEHİR"
      ],
      "ŞIRNAK": [
        "BEYTÜŞŞEBAP",
        "CİZRE",
        "GÜÇLÜKONAK",
        "İDİL",
        "MERKEZ",
        "SİLOPİ",
        "ULUDERE"
      ],
      "TEKİRDAĞ": [
        "ÇERKEZKÖY",
        "ÇORLU",
        "ERGENE",
        "HAYRABOLU",
        "KAPAKLI",
        "MALKARA",
        "MARMARAEREĞLİSİ",
        "MURATLI",
        "SARAY",
        "SÜLEYMANPAŞA",
        "ŞARKÖY"
      ],
      "TOKAT": [
        "ALMUS",
        "ARTOVA",
        "BAŞÇİFTLİK",
        "ERBAA",
        "MERKEZ",
        "NİKSAR",
        "PAZAR",
        "REŞADİYE",
        "SULUSARAY",
        "TURHAL",
        "YEŞİLYURT",
        "ZİLE"
      ],
      "TRABZON": [
        "AKÇAABAT",
        "ARAKLI",
        "ARSİN",
        "BEŞİKDÜZÜ",
        "ÇARŞIBAŞI",
        "ÇAYKARA",
        "DERNEKPAZARI",
        "DÜZKÖY",
        "HAYRAT",
        "KÖPRÜBAŞI",
        "MAÇKA",
        "OF",
        "ORTAHİSAR",
        "SÜRMENE",
        "ŞALPAZARI",
        "TONYA",
        "VAKFIKEBİR",
        "YOMRA"
      ],
      "TUNCELİ": [
        "ÇEMİŞGEZEK",
        "HOZAT",
        "MAZGİRT",
        "MERKEZ",
        "NAZIMİYE",
        "OVACIK",
        "PERTEK",
        "PÜLÜMÜR"
      ],
      "UŞAK": [
        "BANAZ",
        "EŞME",
        "KARAHALLI",
        "MERKEZ",
        "SİVASLI",
        "ULUBEY"
      ],
      "VAN": [
        "BAHÇESARAY",
        "BAŞKALE",
        "ÇALDIRAN",
        "ÇATAK",
        "EDREMİT",
        "ERCİŞ",
        "GEVAŞ",
        "GÜRPINAR",
        "İPEKYOLU",
        "MURADİYE",
        "ÖZALP",
        "SARAY",
        "TUŞBA"
      ],
      "YALOVA": [
        "ALTINOVA",
        "ARMUTLU",
        "ÇINARCIK",
        "ÇİFTLİKKÖY",
        "MERKEZ",
        "TERMAL"
      ],
      "YOZGAT": [
        "AKDAĞMADENİ",
        "AYDINCIK",
        "BOĞAZLIYAN",
        "ÇANDIR",
        "ÇAYIRALAN",
        "ÇEKEREK",
        "KADIŞEHRİ",
        "MERKEZ",
        "SARAYKENT",
        "SARIKAYA",
        "SORGUN",
        "ŞEFAATLİ",
        "YENİFAKILI",
        "YERKÖY"
      ],
      "ZONGULDAK": [
        "ALAPLI",
        "ÇAYCUMA",
        "DEVREK",
        "EREĞLİ",
        "GÖKÇEBEY",
        "KİLİMLİ",
        "KOZLU",
        "MERKEZ"
      ]
};

const Register = () => {
  const [email, setEmail] = useState('');
  const [pharmacyName, setPharmacyName] = useState('');
  const [password, setPassword] = useState('');
  const [city, setCity] = useState('');
  const [district, setDistrict] = useState('');
  const [phoneNumber, setPhoneNumber] = useState('');
  const [cities, setCities] = useState(Object.keys(allCitiesAndDistricts));
  const [districts, setDistricts] = useState([]);

  // Seçilen şehire göre ilçeleri güncelleme
  useEffect(() => {
    setDistricts(city ? allCitiesAndDistricts[city] : []);
  }, [city]);

  const handleSubmit = (event) => {
    event.preventDefault();
    console.log(`Email: ${email}, Pharmacy Name: ${pharmacyName}, Password: ${password}, City: ${city}, District: ${district}, Phone Number: ${phoneNumber}`);
    // Burada gerçek bir kayıt işlemi yapılabilir (örneğin, bir API çağrısı)
  };

  return (
    <div className="register-container">
      <h2>Register</h2>
      <form className="register-form" onSubmit={handleSubmit}>
        {/* Email, Pharmacy Name, Password, Phone Number Input Alanları */}
        <div className="input-group">
          <label htmlFor="email">Email:</label>
          <input type="email" id="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
        </div>
        <div className="input-group">
          <label htmlFor="pharmacyName">Pharmacy Name:</label>
          <input type="text" id="pharmacyName" value={pharmacyName} onChange={(e) => setPharmacyName(e.target.value)} required />
        </div>
        <div className="input-group">
          <label htmlFor="password">Password:</label>
          <input type="password" id="password" value={password} onChange={(e) => setPassword(e.target.value)} required />
        </div>
        <div className="input-group">
          <label htmlFor="phoneNumber">Phone Number:</label>
          <input type="text" id="phoneNumber" value={phoneNumber} onChange={(e) => setPhoneNumber(e.target.value)} required />
        </div>

        {/* City ve District Seçim Alanları */}
        <div className="input-group">
          <label htmlFor="city">City:</label>
          <select id="city" value={city} onChange={(e) => setCity(e.target.value)} required>
            <option value="">Select a city</option>
            {cities.map((cityName) => (
              <option key={cityName} value={cityName}>{cityName}</option>
            ))}
          </select>
        </div>
        <div className="input-group">
          <label htmlFor="district">District:</label>
          <select id="district" value={district} onChange={(e) => setDistrict(e.target.value)} required>
            <option value="">Select a district</option>
            {districts.map((districtName) => (
              <option key={districtName} value={districtName}>{districtName}</option>
            ))}
          </select>
        </div>

        <button type="submit">Submit</button>
      </form>
    </div>
  );
};

export default Register
